##### TAG DEFINITION OF ENVIRONMENT #####
# [NAME, SIZE(m), X(m), Y(m), Z(m), psi(Deg)]
TAG_TRUE_RT:
  TAGS:
  ### CROSSROAD01
    - ["SIGNBOARD01", 0.020, -2.00, -2.135, 0.365, 270.0]
    - ["SIGNBOARD04", 0.020, -1.88, -2.250, 0.365, 180.0]

  ### CROSSROAD02
    - ["SIGNBOARD02", 0.020, -2.00, 00.635, 0.365, 090.0]
    - ["SIGNBOARD03", 0.020, -2.00, 00.865, 0.365, 270.0]
    - ["SIGNBOARD05", 0.020, -1.88, 00.750, 0.365, 180.0]

  ### CROSSROAD03
    - ["SIGNBOARD06", 0.020, -0.12, -2.250, 0.365, 000.0]
    - ["SIGNBOARD08", 0.020, 00.00, -2.135, 0.365, 270.0]
    - ["SIGNBOARD10", 0.020, 00.12, -2.250, 0.365, 180.0]

  ### CROSSROAD04
    - ["SIGNBOARD07", 0.020, -0.12, 00.750, 0.365, 000.0]
    - ["SIGNBOARD09", 0.020, 00.00, 00.635, 0.365, 090.0]
    - ["SIGNBOARD11", 0.020, 00.12, 00.750, 0.365, 180.0]

  ### CROSSROAD05
    - ["SIGNBOARD12", 0.020, 01.88, -2.250, 0.365, 000.0]
    - ["SIGNBOARD14", 0.020, 02.00, -2.135, 0.365, 270.0]

  ### CROSSROAD06
    - ["SIGNBOARD13", 0.020, 01.88, 00.750, 0.365, 000.0]
    - ["SIGNBOARD15", 0.020, 02.00, 00.635, 0.365, 090.0]
    - ["SIGNBOARD16", 0.020, 02.00, 00.865, 0.365, 270.0]