##### TAG DEFINITION OF ENVIRONMENT #####
# [NAME, SIZE(m), X(m), Y(m), Z(m), psi(Deg)]
TAG_TRUE_RT:
  TAGS:
  ### CROSSROAD01
    - ["SIGNBOARD01", 0.021, -2.00, -2.63, 0.325, 270.0]
    - ["SIGNBOARD04", 0.021, -1.88, -2.75, 0.325, 180.0]

  ### CROSSROAD02
    - ["SIGNBOARD02", 0.021, -2.00, 00.63, 0.325, 090.0]
    - ["SIGNBOARD03", 0.021, -2.00, 00.87, 0.325, 270.0]
    - ["SIGNBOARD05", 0.021, -1.88, 00.75, 0.325, 180.0]

  ### CROSSROAD03
    - ["SIGNBOARD06", 0.021, -0.12, -2.75, 0.325, 000.0]
    - ["SIGNBOARD08", 0.021, 00.00, -2.63, 0.325, 270.0]
    - ["SIGNBOARD10", 0.021, 00.12, -2.75, 0.325, 180.0]

  ### CROSSROAD04
    - ["SIGNBOARD07", 0.021, -0.12, 00.75, 0.325, 000.0]
    - ["SIGNBOARD09", 0.021, 00.00, 00.63, 0.325, 090.0]
    - ["SIGNBOARD11", 0.021, 00.12, 00.75, 0.325, 180.0]

  ### CROSSROAD05
    - ["SIGNBOARD12", 0.021, 01.88, -2.75, 0.325, 000.0]
    - ["SIGNBOARD14", 0.021, 02.00, -2.63, 0.325, 270.0]

  ### CROSSROAD06
    - ["SIGNBOARD13", 0.021, 01.88, 00.75, 0.325, 000.0]
    - ["SIGNBOARD15", 0.021, 02.00, 00.63, 0.325, 090.0]
    - ["SIGNBOARD16", 0.021, 02.00, 00.87, 0.325, 270.0]