# config/costmap_common_params.yaml

obstacle_range: 2.5
raytrace_range: 3.0

# Perkiraan footprint Nexus (sesuaikan kalau tahu ukuran pastinya)
footprint: [[0.20, 0.14],
            [0.20,-0.14],
            [-0.20,-0.14],
            [-0.20, 0.14]]

inflation_radius: 0.30
cost_scaling_factor: 5.0

# Sensor yang dipakai untuk obstacle
observation_sources: depth_points

depth_points:
  data_type: PointCloud2
  topic: /camera/depth/points    # GANTI kalau topiknya beda
  marking: true
  clearing: true
  obstacle_range: 2.5
  raytrace_range: 3.0
  min_obstacle_height: 0.05
  max_obstacle_height: 1.5
